heat_template_version: 2013-05-23

description: |
  This is a Heat template to deploy a single Linux server running a rails
  application deployed from a git repo

parameters:
  server_hostname:
    label: Server Hostnames
    description: Defines how the server will be named.
    type: string
    default: 'mongo-%index%'

  image:
    label: Operating System
    description: |
      Server image used for all servers that are created as a part of this
      deployment
    type: string
    default: Ubuntu 12.04 LTS (Precise Pangolin)
    constraints:
    - allowed_values:
      - Ubuntu 12.04 LTS (Precise Pangolin)
      description: Must be a supported operating system.

  flavor:
    label: Server Size
    description: |
      Rackspace Cloud Server flavor to use. The size is based on the amount of
      RAM for the provisioned server.
    type: string
    default: 4 GB Performance
    constraints:
    - allowed_values:
      - 1 GB Performance
      - 2 GB Performance
      - 4 GB Performance
      - 8 GB Performance
      - 15 GB Performance
      - 30 GB Performance
      - 1GB Standard Instance
      - 2GB Standard Instance
      - 4GB Standard Instance
      - 8GB Standard Instance
      - 15GB Standard Instance
      - 30GB Standard Instance
      description: |
        Must be a valid Rackspace Cloud Server flavor for the region you have
        selected to deploy into.

  child_template:
    label: Child Template
    description: |
      Location of the child template to use for the Rails application servers
    type: string
    default: http://drop.duncancreek.net/mongodb-replset-peers.yaml
#    default: https://raw.githubusercontent.com/JasonBoyles/heat-mongodb-replicaset/master/mongodb-replset-peers.yaml

  peer_server_count:
    label: number of additional peer servers to build
    type: number
    default: 2

  kitchen:
    description: "URL for a git repo containing required cookbooks"
    type: string
    default: https://github.com/JasonBoyles/heat-mongodb-replicaset

  chef_version:
    description: Version of chef client to use
    type: string
    default: 10.24.0

resources:

  ssh_key:
    type: "OS::Nova::KeyPair"
    properties:
      name: { get_param: "OS::stack_id" }
      save_private_key: true

  mongodb_peer_servers:
    type: "OS::Heat::ResourceGroup"
    properties:
      count: { get_param: peer_server_count }
      resource_def:
        type: { get_param: child_template }
        properties:
          server_hostname: { get_param: server_hostname }
          image: { get_param: image }
          flavor: { get_param: flavor }
          ssh_key: { get_resource: ssh_key }
          ssh_private_key: { get_attr: [ssh_key, private_key] }
          kitchen: { get_param: kitchen }

  mongodb_initial_server:
    type: "Rackspace::Cloud::Server"
    properties:
      name: { get_param: server_hostname }
      flavor: { get_param: flavor }
      image: { get_param: image }
      key_name: { get_resource: ssh_key }
      config_drive: "true"

  server_setup:
    type: "OS::Heat::ChefSolo"
    depends_on:
    - mongodb_initial_server
    - mongodb_peer_servers
    properties:
      username: root
      private_key: { get_attr: [ssh_key, private_key] }
      host: { get_attr: [mongodb_initial_server, accessIPv4] }
      kitchen: { get_param: kitchen }
      chef_version: { get_param: chef_version }
      node:
        mongodb:
          bind_ip: { get_attr: [mongodb_initial_server, privateIPv4] }
          use_fqdn: false
          replicaset_members: { get_attr: [mongodb_peer_servers, privateIPv4] }
        run_list: [ "recipe[mongodb::10gen_repo]",
                    "recipe[mongodb::replicaset]" ]

outputs:
  private_key:
    value: { get_attr: [ssh_key, private_key] }
    description: "SSH Private Key"

  server_public_ip:
    value: { get_attr: [mongodb_initial_server, accessIPv4] }
    description: "Server IP"

  peer_private_ips:
    value: { get_attr: [mongodb_peer_servers, privateIPv4] }
    description: "peer private IPs"
